import Head from 'next/head'
import { useEffect, useState } from 'react';
import LineChart from './lineChart';

export default function Home() {
  // react hooks para poder almacenar los datos que estoy trayendo
  const [labl, setLabl] = useState([])
  const [labl2, setLabl2] = useState([]) // para rodolfo
  const [valores, setValores] = useState([])
  const [valores2, setValores2] = useState([]) // para rodolfo
  const [contador, setContador] = useState(0)
  const [seconds, setSeconds] = useState(0);
  const [contador2, setContador2] = useState(0) // para rodolfo
  const [data, setData] = useState({
    labels: [],
    datasets: [
      {
        label: 'Data',
        data: [],
        fill: false,
        borderColor: 'rgb(75, 192, 192)',
        tension: 0.1,
      },
    ],
  });
  const [data2, setData2] = useState({
    labels: [],
    datasets: [
      {
        label: 'Data',
        data: [],
        fill: false,
        borderColor: 'rgb(75, 192, 192)',
        tension: 0.1,
      },
    ],
  });
  // otro react hook llamado useEffect
  useEffect(() => {
    const timer = setInterval(() => {
      setSeconds((prevSeconds) => prevSeconds + 1);
    }, 1000);
    return () => clearInterval(timer);
  }, []);


  const activar = async () => {
    const response = await fetch("/api/hello", {
      method: "GET",
      headers: {
        "Content-Type": "application/json",
      },
    });
    const data2 = await response.json();
    // el [...valores, data2.length] el primer "...valores" trae un historico, el data2.length es el nuevo valor
    setValores([...valores, data2.length])
    setLabl([...labl, contador])
    setContador(contador + 1)
    if (response.status !== 200) {
      throw data.error || new Error(`Request failed with status ${response.status}`);
    }
  }

  // para rodolfo
  const activar2 = async () => {
    const response = await fetch("/api/rodolfo", {
      method: "GET",
      headers: {
        "Content-Type": "application/json",
      },
    });
    const data2 = await response.json();
    let newData = {}
    if (labl.length > 0) {
      console.log("entro2")
    }
    setValores2([...valores2, data2.length])
    setLabl2([...labl2, contador2])
    setContador2(contador2 + 1)
    if (response.status !== 200) {
      throw data.error || new Error(`Request failed with status ${response.status}`);
    }
  }

  useEffect(() => {
    activar()
    activar2()
  }, [seconds])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1 className='flexear centrar'>Cantidad de datos en el tiempo</h1>
        <div className='grilla'>
          <div>
            <h1>Clientes</h1>
            <div className='altura'><LineChart valores={valores} etiquetas={labl} /></div>
          </div>
          <div>
            <h1>Compras</h1>
            <div className='altura'><LineChart valores={valores2} etiquetas={labl2} /></div>
          </div>
        </div>

      </div>
    </>
  )
}
